# Generated by Django 5.1.5 on 2025-01-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillDetails',
            fields=[
                ('bill_no', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(max_length=255)),
                ('balance', models.IntegerField(max_length=255)),
            ],
        ),
    ]
