# Generated by Django 5.1.5 on 2025-01-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billdetails',
            name='balance',
        ),
        migrations.AddField(
            model_name='billdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='billdetails',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
