# Generated by Django 5.1.5 on 2025-01-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_remove_billdetails_balance_billdetails_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetails',
            name='amount_paid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='billdetails',
            name='balance_amount',
            field=models.IntegerField(null=True),
        ),
    ]
