# Generated by Django 5.1.5 on 2025-01-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_billdetails_amount_paid_billdetails_balance_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdetails',
            name='amount_paid',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
